FROM ubuntu:latest

LABEL maintainer="sethuram975351 <sethuram500@gmail.com>"

RUN apt-get update  && \
    apt-get install -y python3-dev python3-pip

RUN  apt-get install -y python3-psycopg2


WORKDIR /smart_share 


COPY requirement.txt requirement.txt
RUN pip3 install -r requirement.txt

# copy source code comlpete package to working directory along with requirement.txt
COPY . /smart_share 


EXPOSE 5001
EXPOSE 5002
EXPOSE 5003
EXPOSE 5004
EXPOSE 5005


# have to run the startup script 
#CMD [ "./startup.sh" ]
